services:
  # mysql_gateway


  # mysql_auth
  mysql_auth:
    image: mysql:8.0
    container_name: mysql_auth
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=auth_db
    ports:
      - "3301:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    networks:
      - my-shared-network


  # mysql_profile


volumes:
  #mysql_gateway_data:
  mysql_auth_data:
  #mysql_profile_data:

networks:
  my-shared-network:
    external: true